# Generated by Django 3.2.12 on 2022-02-04 14:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('experiment_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('experiment_name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('problem_type', models.CharField(max_length=100, null=True)),
                ('target', models.CharField(max_length=1000, null=True)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100000), blank=True, null=True, size=None)),
                ('datasource_id', models.CharField(max_length=1000, null=True)),
                ('datasource_name', models.CharField(max_length=1000, null=True)),
                ('score', models.CharField(max_length=200, null=True)),
                ('algorithm_presets', models.CharField(max_length=200, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_delete', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('model_type', models.CharField(max_length=300, null=True)),
                ('model_name', models.CharField(max_length=300, null=True)),
                ('val_score', models.FloatField(null=True)),
                ('test_score', models.FloatField(null=True)),
                ('fit_time', models.FloatField(null=True)),
                ('predict_time', models.FloatField(null=True)),
                ('feature_importance', models.JSONField(null=True)),
                ('stack_level', models.FloatField(null=True)),
                ('predict_label_encode', models.JSONField(null=True)),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.IntegerField(null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('start_datetime', models.DateTimeField(null=True)),
                ('finish_datetime', models.DateTimeField(null=True)),
                ('percent_completed', models.IntegerField(null=True)),
                ('runtime_estimate', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('predict_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('predict_name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('datasource_id', models.CharField(max_length=200, null=True)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.model')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task'),
        ),
    ]
