# Generated by Django 3.2.12 on 2022-02-05 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('file_path', models.CharField(max_length=200, null=True)),
                ('file_url', models.CharField(max_length=200, null=True)),
                ('is_delete', models.BooleanField(null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.file'),
        ),
    ]
