# Generated by Django 3.2.12 on 2022-02-07 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_filemetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.file'),
        ),
    ]
