# Generated by Django 3.2.12 on 2022-02-07 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_filemetadata_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='percent_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='runtime_estimate',
        ),
        migrations.AddField(
            model_name='file',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task'),
        ),
    ]
