# Generated by Django 3.2.12 on 2022-02-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220207_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='datasource_id',
            new_name='split_ratio',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='datasource_name',
        ),
    ]
