# Generated by Django 3.1.1 on 2022-02-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_experiment_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='test_score',
            new_name='score_test',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='val_score',
            new_name='score_val',
        ),
    ]
