# Generated by Django 3.1.1 on 2022-02-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220210_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='score_test',
            new_name='test_score',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='score_val',
            new_name='val_score',
        ),
    ]
