# Generated by Django 3.1.1 on 2022-02-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220210_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='test_score',
            new_name='score_test',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='val_score',
            new_name='score_val',
        ),
    ]
