# Generated by Django 3.1.1 on 2022-02-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220213_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='is_delete',
            field=models.BooleanField(null=True),
        ),
    ]
