# Generated by Django 3.1.1 on 2022-02-17 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_predict_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEda',
            fields=[
                ('file_eda_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.file')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
    ]
