# Generated by Django 3.1.1 on 2022-02-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_fileeda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileeda',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='file_eda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fileeda'),
        ),
    ]
