# Generated by Django 3.1.1 on 2022-02-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_evaluation_predict_vs_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationClass',
            fields=[
                ('evaluation_class_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('evaluation_class_name', models.CharField(max_length=200, null=True)),
                ('evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationClassScore',
            fields=[
                ('evaluation_class_score_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('scores', models.JSONField(null=True)),
                ('evaluation_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.evaluationclass')),
            ],
        ),
    ]
