# Generated by Django 3.1.1 on 2022-03-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20220228_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationClassDistribution',
            fields=[
                ('evaluation_class_distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('predict_distribution', models.JSONField(null=True)),
                ('evaluation_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.evaluationclass')),
            ],
        ),
    ]
