# Generated by Django 3.1.1 on 2022-03-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_evaluationclassdistribution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvaluationClassScore',
            new_name='EvaluationClassRocLift',
        ),
        migrations.RenameField(
            model_name='evaluationclassroclift',
            old_name='evaluation_class_score_id',
            new_name='evaluation_class_roc_lift_id',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='predict_vs_actual',
        ),
        migrations.CreateModel(
            name='EvaluationPredictActual',
            fields=[
                ('evaluation_predict_actual_id', models.AutoField(primary_key=True, serialize=False)),
                ('predict_vs_actual', models.JSONField(null=True)),
                ('evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.evaluation')),
            ],
        ),
    ]
