# Generated by Django 3.1.1 on 2022-03-12 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20220310_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSubPopulation',
            fields=[
                ('sub_population_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_population', models.JSONField(null=True)),
                ('evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.evaluation')),
                ('file_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.filemetadata')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
    ]
