# Generated by Django 3.1.1 on 2022-03-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_evaluationsubpopulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationsubpopulation',
            name='sub_population_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
