# Generated by Django 3.1.1 on 2022-03-15 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20220312_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explain',
            fields=[
                ('explain_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.evaluation')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
        migrations.CreateModel(
            name='ExplainPdp',
            fields=[
                ('explain_pdp_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=100, null=True)),
                ('explain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.explain')),
            ],
        ),
        migrations.CreateModel(
            name='ExplainPdpClass',
            fields=[
                ('explain_pdp_class_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100, null=True)),
                ('explain_pdp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.explainpdp')),
            ],
        ),
        migrations.CreateModel(
            name='ExplainPdpRegress',
            fields=[
                ('explain_pdp_regress_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdp_values', models.JSONField(null=True)),
                ('explain_pdp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.explainpdp')),
            ],
        ),
        migrations.CreateModel(
            name='ExplainPdpClassValues',
            fields=[
                ('pdp_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdp_values', models.JSONField(null=True)),
                ('explain_pdp_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.explainpdpclass')),
            ],
        ),
    ]
