# Generated by Django 3.1.1 on 2022-03-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_explain_explainpdp_explainpdpclass_explainpdpclassvalues_explainpdpregress'),
    ]

    operations = [
        migrations.AddField(
            model_name='explainpdpclass',
            name='pdp_values',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='ExplainPdpClassValues',
        ),
    ]
