# Generated by Django 3.1.1 on 2022-03-16 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20220316_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explainpdpclass',
            name='pdp_values',
        ),
        migrations.CreateModel(
            name='ExplainPdpClassValues',
            fields=[
                ('pdp_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdp_values', models.JSONField(null=True)),
                ('explain_pdp_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.explainpdpclass')),
            ],
        ),
    ]
